name: AIAssistant
options:
  bundleIdPrefix: com.henry
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"
  OpenAI:
    url: https://github.com/MacPaw/OpenAI
    from: "0.4.0"

targets:
  AIAssistant:
    type: application
    platform: macOS
    sources:
      - path: Sources
    resources:
      - path: Resources
    dependencies:
      - package: KeyboardShortcuts
      - package: OpenAI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.henry.AIAssistant
        PRODUCT_NAME: AIAssistant
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/AIAssistant.entitlements
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"

  AIAssistantTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/UnitTests
    dependencies:
      - target: AIAssistant
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.henry.AIAssistant.Tests
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: "YES"
